dist: trusty
sudo: false
 
language: node_js
node_js:
  - "8"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
 
cache:
  directories:
     - ./node_modules
 
install:
  - npm install
 
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm build --prod --base-href https://cexagupta.github.io/angular-test-app/
 deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/test-angular-app
  on:
    branch: master
