language: node_js
node_js:
  - "10.15.3"
dist: "trusty"
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng lint
  - ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ng build --prod --base-href https://cexagupta.github.io/angular-test-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/test-angular-app
  on:
    branch: master
